export const productData = {
  brand: "Ayurnnath",
  productName: "Private Knight Combo",
  tagline: "Power & Performance Redefined — Ayurvedic combo designed to boost confidence, stamina, and performance naturally.",
  phone: "+917547996250",
  whatsapp: "917547996250",
  website: "www.ayurnnath.com",
  pricing: {
    original: 2700,
    discounted: 1799,
    currency: "INR",
    savePercent: 33,
  },
  badges: [
    "Cash On Delivery",
    "ISO Certified",
    "Trusted by 1 Lakh+ Customers",
    "100% Ayurvedic",
    "GMP Certified",
    "FSSAI Approved",
  ],
  licenses: [
    { id: "iso", icon: "🏅", title: "ISO", desc: "International quality management standards — verified and compliant." },
    { id: "gmp", icon: "✅", title: "GMP", desc: "Good Manufacturing Practice — produced in a certified hygienic facility." },
    { id: "fssai", icon: "🌿", title: "FSSAI", desc: "Food Safety & Standards Authority of India — safe for human consumption." },
  ],
  comboItems: [
    {
      id: "capsules",
      name: "Private Knight Capsules",
      qty: "60 Capsules",
      benefits: ["Long-Lasting Stamina", "Builds Instant Energy", "Boosts Desire & Confidence"],
    },
    {
      id: "oil",
      name: "Private Knight Oil",
      qty: "50ml",
      benefits: ["Increases Libido Naturally", "Improves Hardness", "Enhances Organ Size"],
    },
  ],
  whyChoose: [
    { icon: "🌿", title: "100% Natural", desc: "Made from fresh herbs only. No synthetic ingredients, no harmful chemicals — just pure nature." },
    { icon: "🧪", title: "No Extracts Used", desc: "Whole, pure herbs without artificial extracts or additives for maximum effectiveness." },
    { icon: "🏅", title: "GMP Certified Unit", desc: "Manufactured in a certified facility that follows strict quality and safety standards." },
    { icon: "♻️", title: "BPA-Free Packaging", desc: "Packed in safe, toxin-free packaging to protect your health and the environment." },
  ],
  whyItWorks: [
    { num: 1, title: "Natural Ayurvedic Ingredients", desc: "Time-tested herbs known to support vitality, metabolism, and overall wellness." },
    { num: 2, title: "Scientifically Backed Formula", desc: "Developed with expert input and modern research to maximize absorption and results." },
    { num: 3, title: "No Side Effects", desc: "Free from harmful chemicals and artificial additives — safe for long-term use." },
    { num: 4, title: "Holistic Health Benefits", desc: "Improves your body's natural balance from within, not just surface-level symptoms." },
  ],
  highlights: [
    { icon: "🎨", label: "No Artificial Colors" },
    { icon: "♻️", label: "BPA Free" },
    { icon: "🚚", label: "Fast Shipping" },
    { icon: "⭐", label: "Trusted Quality" },
    { icon: "🌿", label: "Natural Herbs" },
    { icon: "🚫", label: "No Added Sugar" },
    { icon: "🏅", label: "GMP Certified" },
    { icon: "✅", label: "No Extracts Used" },
  ],
  deliverySteps: [
    { icon: "🏭", label: "Made in Our Factory" },
    { icon: "🎁", label: "Packed with Love" },
    { icon: "🚚", label: "Shipped Across India" },
    { icon: "🏠", label: "Delivered to Your Doorstep" },
  ],
  dosage: {
    capsules: "Take 1–2 capsules daily with warm milk or water. Best taken after meals for optimal absorption.",
    oil: "Apply a few drops and massage gently for 5–10 minutes. Use regularly for best visible results.",
  },
  languages: {
    en: {
      title: "Ultimate Duo for Men Who Want More",
      sub: "Regain confidence, passion & unstoppable energy",
      body: "Private Knight Capsules & Oil — a special Ayurvedic blend that naturally improves performance and stamina.",
      capsuleBenefits: ["Long-Lasting Stamina", "Builds Instant Energy", "Boosts Desire & Confidence"],
      oilBenefits: ["Increases Libido Naturally", "Improves Hardness", "Enhances Organ Size"],
    },
    hi: {
      title: "Private Knight Combo – ताकत और प्रदर्शन की नई पहचान",
      sub: "उन पुरुषों के लिए बेहतरीन जो और ज़्यादा चाहते हैं!",
      body: "Ayurnnath Private Knight Combo के साथ आत्मविश्वास, जुनून और ऊर्जा वापस पाएं। यह आयुर्वेदिक संयोजन प्रदर्शन और स्टैमिना को प्राकृतिक रूप से बेहतर बनाता है।",
      capsuleBenefits: ["लंबे समय तक स्टैमिना", "तुरंत ऊर्जा देता है", "इच्छा और आत्मविश्वास बढ़ाता है"],
      oilBenefits: ["प्राकृतिक रूप से लिबिडो बढ़ाता है", "कठोरता सुधारता है", "अंग के आकार को बेहतर बनाता है"],
    },
    bn: {
      title: "Private Knight Combo – শক্তি ও পারফরম্যান্সের নতুন সংজ্ঞা",
      sub: "যারা আরও বেশি চান, তাদের জন্য চূড়ান্ত ডুয়ো!",
      body: "Ayurnnath Private Knight Combo-র সাথে ফিরে পান আত্মবিশ্বাস ও অদম্য শক্তি। এই বিশেষ আয়ুর্বেদিক সংমিশ্রণ প্রাকৃতিকভাবে পারফরম্যান্স ও স্ট্যামিনা উন্নত করে।",
      capsuleBenefits: ["দীর্ঘস্থায়ী স্ট্যামিনা", "দ্রুত শক্তি জোগায়", "আত্মবিশ্বাস ও ইচ্ছাশক্তি বৃদ্ধি করে"],
      oilBenefits: ["প্রাকৃতিকভাবে লিবিডো বৃদ্ধি করে", "দৃঢ়তা বাড়ায়", "অঙ্গের আকার উন্নত করে"],
    },
  },
  reviews: {
    rating: 4.7,
    count: 218,
    summary: "Capsules + Oil — Real experiences from real buyers",
    items: [
      { initials: "SD", name: "Subhajit Das", location: "Kolkata, WB", rating: 5, text: "sotti bolte prothome bisshwas hoyni .. onloine eto product dekhi shob voya mone hoy . kintu bondhur kotha y ei combo order korlam . 3 shoptaho pore সত্যিই পার্থক্য bujhte parcchi . energy onek berecche , ar klanti ager moto nei . packeging ekdom sadamata chilo barie keu bujhte i pareni 😄 abar order korbo", category: "Community Review", date: "8 Jan 2025" },
      { initials: "PM", name: "Prosenjit Mondal", location: "Howrah, WB", rating: 5, text: "dada ei product aktu derite try korlam kintu result dekhe mone hocche aro age korle valo hoto . capsule ar oil duTo ekkoshathe use korchi 1 maash dhore .. stamina ebong confidance duToi imporve hoyeche . কোনো সাইড এফেক্ট নেই . ful marks 👍", category: "User Experience", date: "14 Jan 2025" },
      { initials: "AG", name: "Arpan Ghosh", location: "Durgapur, WB", rating: 4, text: "valo product .. ami engineer kaj er chape shorir ekdom venge porchilo . rate ghuomer poreo klanti jeto na . Private Knight Capsules suru korar pore shokal e uthe energitic feel hocche . oilta o valo herbal gondho ache kintu jwala kore na .. delivary aktu deri tai 4 star", category: "Buyer Comment", date: "21 Jan 2025" },
      { initials: "TB", name: "Tanmoy Biswas", location: "Siliguri, WB", rating: 5, text: "amar boyos 38 , got koyekbochor dhore shorire ar ager moto jor pacchilam na . ডাক্তারের কাছে যেতে লজ্জা লাগছিল। tokhon ei combo dekhlam online e . shompurno ayurvedic dekhe shahos kore order korlam . 45 din por bolte pari — eta shotti kaj kore . Ayurnath ke অনেক ধন্যবাদ 🙏", category: "Community Review", date: "29 Jan 2025" },
      { initials: "RS", name: "Rajib Sarkar", location: "Barrackpore, WB", rating: 5, text: "packetta esechilo ekdom shada packegig e .. baire kichui lekha nei . eta dekhe i bujhlam company privasy bujhe . oilta masaaj korle gorom onuvuti hoy khub aaramdayok . 30 din e i result bojha jacche .. দারুণ প্রোডাক্ট — ekbar try i kore dekhun !! 😊", category: "User Experience", date: "5 Feb 2025" },
      { initials: "SR", name: "Sougata Roy", location: "Asansol, WB", rating: 5, text: "ami onek kichu try korechi age — kichui kaj koreni . sheshmesh ei Private Knight Combo .. এবার হতাশ হইনি !!! tin shoptathe i parthokko ter pacchi . stri o bollen porivortton bujhte parchhen 😄 ar ki lage ! dwitio pack order kore diyechi already", category: "Community Review", date: "11 Feb 2025" },
      { initials: "DP", name: "Debashis Paul", location: "Krishnanagar, WB", rating: 4, text: "এখনো full result পাইনি .. 2 week holo use korchi . enargy aktu better feel hocche . oil masaaj korle rilaksd lage .. customar servise o valo . দেখি আরো চলবে কিনা 🙂", category: "Buyer Comment", date: "18 Feb 2025" },
      { initials: "BC", name: "Biswanath Chatterjee", location: "Burdwan, WB", rating: 5, text: "shotto review dicchi — amar boyos 44 . এই বয়সে শরীর যা হয় সবাই বোঝেন। Private Knight Capsule ar Oil ekkosathe byabohar kore ami shotti obak hoye gechi !! 6 shoptaho por mone hocche 30 bochor boyoshe fire gechi 😁 kono chemicall nei kono khoti nei . Ayurnath দীর্ঘজীবী হোক 🙏", category: "User Experience", date: "25 Feb 2025" },
      { initials: "MH", name: "Mithun H.", location: "Malda, WB", rating: 5, text: "valo .. packaging discreet chilo 👍 difference ache use korchi", category: "Buyer Comment", date: "4 Mar 2025" },
      { initials: "PS", name: "Partha S.", location: "Bankura, WB", rating: 3, text: "use korchi .. দেখি আরো order করব . ekhon energy aktu better . 3 star na 5 star bola mushkil ekhone .. aro 2 week use kori tahole bolte parbo", category: "Buyer Comment", date: "10 Mar 2025" },
      { initials: "RK", name: "Rajesh K.", location: "Mumbai, Maharashtra", rating: 5, text: "bhai sach mein kaam karta hai ! was very skeptical at first but after 3 weeks using both capsule and oil together .. energy levels much better and confidance is back . packaging was also very discreet . will order again", category: "Community Review", date: "12 Jan 2025" },
      { initials: "SM", name: "Suresh M.", location: "Hyderabad, Telangana", rating: 5, text: "excellent product . tried many ayurvedic products before but this combo is diffrent . oil absorbs quickly and capsules dont have bad smell or taste . after one month stamina improved alot . wife also noticced the difference 😄 highly recomended", category: "User Experience", date: "28 Jan 2025" },
      { initials: "AT", name: "Amit T.", location: "Delhi", rating: 4, text: "good product overall . results started showing after 2nd week . capsules easy to swallow , take with warm milk at night as suggested . oil massage also feels good .. gave 4 stars only because delivery took 6 days but product quality is 5 star", category: "Buyer Comment", date: "3 Feb 2025" },
      { initials: "VS", name: "Vikram S.", location: "Pune, Maharashtra", rating: 5, text: "was feeling very tired and low energy for past few months . friend recommended this combo and honestly it has been a game changer .. both products together work really well . no side effects at all even after 45 days . 100% natural feel", category: "User Experience", date: "9 Feb 2025" },
      { initials: "MI", name: "Mohammed I.", location: "Bangalore, Karnataka", rating: 5, text: "first time i ordered was nervous about privacy but packagging was completely plain with no product name outside . very profesional . and the product itself — mashallah — working very well . energy and mood both improved . already placed second order 🤲", category: "Community Review", date: "15 Feb 2025" },
      { initials: "DR", name: "Deepak R.", location: "Jaipur, Rajasthan", rating: 4, text: "decent product .. using since 3 weeks only so cannot give full review yet . initial results are promissing . capsules are good quality . oil has nice mild herbal smell . customer service also replied fast . will update review after full course 🙂", category: "Buyer Comment", date: "19 Feb 2025" },
      { initials: "SP", name: "Sanjay P.", location: "Chennai, Tamil Nadu", rating: 5, text: "pehle kai products try kiye the koi result nahi mila . phir yeh combo try kiya and within 20 days energy aane lagi . Oil especially good — thoda sa bhi bahut kaam karta hai . Totally worth money . Ayurnath brand pe trust karta hoon ab 🙏", category: "User Experience", date: "22 Feb 2025" },
      { initials: "RN", name: "Ravi N.", location: "Kolkata, West Bengal", rating: 5, text: "BEST combo i have ever used . work long hours always exhausted by evening . since starting Private Knight capsules feeling energetic whole day . oil also very effective . no burning sensation no irritation — pure herbal . 5 stars without any doubt", category: "Community Review", date: "1 Mar 2025" },
      { initials: "AB", name: "Arjun B.", location: "Lucknow, UP", rating: 4, text: "product is genuine and results are there . worried about chemicals or steroids but this is fully ayurvedic and safe . sleep has also improved since i started . oil massage gives warm sensation during massage which feels very good . minus one star — wish oil bottle was bigger 😅", category: "Buyer Comment", date: "6 Mar 2025" },
      { initials: "HG", name: "Harpreet G.", location: "Amritsar, Punjab", rating: 5, text: "waheguru da shukar hai finally koi product mileya jo actually kaam karda . stamina bahut improve hoya . 30 din de andar farak pata lag gaya . packaging bhi changi si , kisi nu pata nahi chaleya ghar ch ki mangwaya 😂 baki sab samajh jaange . must try", category: "User Experience", date: "11 Mar 2025" },
      { initials: "KD", name: "Kiran D.", location: "Ahmedabad, Gujarat", rating: 4, text: "ekhono FULL result nahi mila .. 3 week holo use korchi . kintu difference ache — energy aktu better . dekhi aro chalbe kina 🙂 packaging discreet chilo seta valo laglo", category: "Buyer Comment", date: "16 Mar 2025" },
      { initials: "TM", name: "Tushar M.", location: "Nagpur, Maharashtra", rating: 5, text: "ordered after seeing ingredients — all ayurvedic no harmful chemicals . am a fitness person very careful about what i put in my body . capsules clean and effective . combined with oil results are visible within 3-4 weeks . genuine product no doubt 💪", category: "Community Review", date: "20 Mar 2025" }
    ],
  },
  faq: [
    { q: "What is inside the Private Knight Combo?", a: "The combo includes Private Knight Capsules (60 caps) and Private Knight Oil (50ml) — a complete Ayurvedic solution for male wellness." },
    { q: "How do I use the capsules?", a: "Take 1–2 capsules daily with warm milk or water, preferably after meals for best results." },
    { q: "How do I use the oil?", a: "Apply a few drops of Private Knight Oil and massage gently for 5–10 minutes. Use regularly for visible results." },
    { q: "Are there any side effects?", a: "No. The formula uses 100% Ayurvedic, natural herbs with zero chemicals and no known side effects. Safe for long-term use." },
    { q: "When will I see results?", a: "Most users notice a difference within a few weeks. For full benefits, consistent use for 2–3 months is recommended." },
    { q: "Is Cash on Delivery available?", a: "Yes! We offer Cash on Delivery across India." },
    { q: "Is this product certified?", a: "Yes, Private Knight Combo is ISO Certified, GMP Certified, and FSSAI approved. Manufactured in a certified Ayurvedic facility." },
  ],
};
