export const productData = {
  brand: "Ayurnnath",
  productName: "Private Knight Combo",
  tagline: "Power & Performance Redefined — Ayurvedic combo designed to boost confidence, stamina, and performance naturally.",
  phone: "+918918541158",
  whatsapp: "918918541158",
  website: "www.ayurnnath.com",
  pricing: {
    original: 2700,
    discounted: 1799,
    currency: "INR",
    savePercent: 33,
  },
  badges: [
    "Cash On Delivery",
    "ISO Certified",
    "Trusted by 1 Lakh+ Customers",
    "100% Ayurvedic",
    "GMP Certified",
    "FSSAI Approved",
  ],
  licenses: [
    { id: "iso", icon: "🏅", title: "ISO", desc: "International quality management standards — verified and compliant." },
    { id: "gmp", icon: "✅", title: "GMP", desc: "Good Manufacturing Practice — produced in a certified hygienic facility." },
    { id: "fssai", icon: "🌿", title: "FSSAI", desc: "Food Safety & Standards Authority of India — safe for human consumption." },
  ],
  comboItems: [
    {
      id: "capsules",
      name: "Private Knight Capsules",
      qty: "60 Capsules",
      benefits: ["Long-Lasting Stamina", "Builds Instant Energy", "Boosts Desire & Confidence"],
    },
    {
      id: "oil",
      name: "Private Knight Oil",
      qty: "50ml",
      benefits: ["Increases Libido Naturally", "Improves Hardness", "Enhances Organ Size"],
    },
  ],
  whyChoose: [
    { icon: "🌿", title: "100% Natural", desc: "Made from fresh herbs only. No synthetic ingredients, no harmful chemicals — just pure nature." },
    { icon: "🧪", title: "No Extracts Used", desc: "Whole, pure herbs without artificial extracts or additives for maximum effectiveness." },
    { icon: "🏅", title: "GMP Certified Unit", desc: "Manufactured in a certified facility that follows strict quality and safety standards." },
    { icon: "♻️", title: "BPA-Free Packaging", desc: "Packed in safe, toxin-free packaging to protect your health and the environment." },
  ],
  whyItWorks: [
    { num: 1, title: "Natural Ayurvedic Ingredients", desc: "Time-tested herbs known to support vitality, metabolism, and overall wellness." },
    { num: 2, title: "Scientifically Backed Formula", desc: "Developed with expert input and modern research to maximize absorption and results." },
    { num: 3, title: "No Side Effects", desc: "Free from harmful chemicals and artificial additives — safe for long-term use." },
    { num: 4, title: "Holistic Health Benefits", desc: "Improves your body's natural balance from within, not just surface-level symptoms." },
  ],
  highlights: [
    { icon: "🎨", label: "No Artificial Colors" },
    { icon: "♻️", label: "BPA Free" },
    { icon: "🚚", label: "Fast Shipping" },
    { icon: "⭐", label: "Trusted Quality" },
    { icon: "🌿", label: "Natural Herbs" },
    { icon: "🚫", label: "No Added Sugar" },
    { icon: "🏅", label: "GMP Certified" },
    { icon: "✅", label: "No Extracts Used" },
  ],
  deliverySteps: [
    { icon: "🏭", label: "Made in Our Factory" },
    { icon: "🎁", label: "Packed with Love" },
    { icon: "🚚", label: "Shipped Across India" },
    { icon: "🏠", label: "Delivered to Your Doorstep" },
  ],
  dosage: {
    capsules: "Take 1–2 capsules daily with warm milk or water. Best taken after meals for optimal absorption.",
    oil: "Apply a few drops and massage gently for 5–10 minutes. Use regularly for best visible results.",
  },
  languages: {
    en: {
      title: "Ultimate Duo for Men Who Want More",
      sub: "Regain confidence, passion & unstoppable energy",
      body: "Private Knight Capsules & Oil — a special Ayurvedic blend that naturally improves performance and stamina.",
      capsuleBenefits: ["Long-Lasting Stamina", "Builds Instant Energy", "Boosts Desire & Confidence"],
      oilBenefits: ["Increases Libido Naturally", "Improves Hardness", "Enhances Organ Size"],
    },
    hi: {
      title: "Private Knight Combo – ताकत और प्रदर्शन की नई पहचान",
      sub: "उन पुरुषों के लिए बेहतरीन जो और ज़्यादा चाहते हैं!",
      body: "Ayurnnath Private Knight Combo के साथ आत्मविश्वास, जुनून और ऊर्जा वापस पाएं। यह आयुर्वेदिक संयोजन प्रदर्शन और स्टैमिना को प्राकृतिक रूप से बेहतर बनाता है।",
      capsuleBenefits: ["लंबे समय तक स्टैमिना", "तुरंत ऊर्जा देता है", "इच्छा और आत्मविश्वास बढ़ाता है"],
      oilBenefits: ["प्राकृतिक रूप से लिबिडो बढ़ाता है", "कठोरता सुधारता है", "अंग के आकार को बेहतर बनाता है"],
    },
    bn: {
      title: "Private Knight Combo – শক্তি ও পারফরম্যান্সের নতুন সংজ্ঞা",
      sub: "যারা আরও বেশি চান, তাদের জন্য চূড়ান্ত ডুয়ো!",
      body: "Ayurnnath Private Knight Combo-র সাথে ফিরে পান আত্মবিশ্বাস ও অদম্য শক্তি। এই বিশেষ আয়ুর্বেদিক সংমিশ্রণ প্রাকৃতিকভাবে পারফরম্যান্স ও স্ট্যামিনা উন্নত করে।",
      capsuleBenefits: ["দীর্ঘস্থায়ী স্ট্যামিনা", "দ্রুত শক্তি জোগায়", "আত্মবিশ্বাস ও ইচ্ছাশক্তি বৃদ্ধি করে"],
      oilBenefits: ["প্রাকৃতিকভাবে লিবিডো বৃদ্ধি করে", "দৃঢ়তা বাড়ায়", "অঙ্গের আকার উন্নত করে"],
    },
  },
  reviews: {
    rating: 4.7,
    count: 218,
    summary: "Capsules + Oil — Real experiences from real buyers",
    items: [
      { initials: "SD", name: "Subhajit Das", location: "Kolkata, WB", rating: 5, text: "sotti bolte prothome bisshwas hoyni .. onloine eto product dekhi shob voya mone hoy . kintu bondhur kotha y ei combo order korlam . 3 shoptaho pore সত্যিই পার্থক্য bujhte parcchi . energy onek berecche , ar klanti ager moto nei . packeging ekdom sadamata chilo barie keu bujhte i pareni 😄 abar order korbo", date: "8 Jan 2025" },
      { initials: "RK", name: "Rajesh K.", location: "Mumbai, Maharashtra", rating: 5, text: "bhai sach mein kaam karta hai ! was very skeptical at first but after 3 weeks using both capsule and oil together .. energy levels much better and confidance is back . packaging was also very discreet . will order again", date: "12 Jan 2025" },
      { initials: "SM", name: "Suresh M.", location: "Hyderabad, Telangana", rating: 5, text: "excellent product . tried many ayurvedic products before but this combo is diffrent . oil absorbs quickly and capsules dont have bad smell or taste . after one month stamina improved alot . wife also noticced the difference 😄 highly recomended", date: "28 Jan 2025" },
      { initials: "RN", name: "Ravi N.", location: "Kolkata, West Bengal", rating: 5, text: "BEST combo i have ever used . work long hours always exhausted by evening . since starting Private Knight capsules feeling energetic whole day . oil also very effective . no burning sensation no irritation — pure herbal . 5 stars without any doubt", date: "1 Mar 2025" },
    ],
  },
  faq: [
    { q: "What is inside the Private Knight Combo?", a: "The combo includes Private Knight Capsules (60 caps) and Private Knight Oil (50ml) — a complete Ayurvedic solution for male wellness." },
    { q: "How do I use the capsules?", a: "Take 1–2 capsules daily with warm milk or water, preferably after meals for best results." },
    { q: "How do I use the oil?", a: "Apply a few drops of Private Knight Oil and massage gently for 5–10 minutes. Use regularly for visible results." },
    { q: "Are there any side effects?", a: "No. The formula uses 100% Ayurvedic, natural herbs with zero chemicals and no known side effects. Safe for long-term use." },
    { q: "When will I see results?", a: "Most users notice a difference within a few weeks. For full benefits, consistent use for 2–3 months is recommended." },
    { q: "Is Cash on Delivery available?", a: "Yes! We offer Cash on Delivery across India." },
    { q: "Is this product certified?", a: "Yes, Private Knight Combo is ISO Certified, GMP Certified, and FSSAI approved. Manufactured in a certified Ayurvedic facility." },
  ],
};
